language: julia
os:
    - linux
julia:
    - release
    - nightly
notifications:
    email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("GeoJSON"); Pkg.test("GeoJSON"; coverage=true)'
after_success:
    - julia -e 'cd(Pkg.dir("GeoJSON")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
